
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Footer': typeof import("../components/Footer.vue")['default']
    'Navbar': typeof import("../components/Navbar.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'Alert': typeof import("../components/ui/alert/index")['Alert']
    'AlertTitle': typeof import("../components/ui/alert/index")['AlertTitle']
    'AlertDescription': typeof import("../components/ui/alert/index")['AlertDescription']
    'AlertDialog': typeof import("../components/ui/alert-dialog/index")['AlertDialog']
    'AlertDialogTrigger': typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
    'AlertDialogContent': typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
    'AlertDialogHeader': typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
    'AlertDialogTitle': typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
    'AlertDialogDescription': typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
    'AlertDialogFooter': typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
    'AlertDialogAction': typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
    'AlertDialogCancel': typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
    'Avatar': typeof import("../components/ui/avatar/index")['Avatar']
    'AvatarImage': typeof import("../components/ui/avatar/index")['AvatarImage']
    'AvatarFallback': typeof import("../components/ui/avatar/index")['AvatarFallback']
    'Badge': typeof import("../components/ui/badge/index")['Badge']
    'Breadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'BreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'BreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'BreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'BreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'BreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'BreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'Button': typeof import("../components/ui/button/index")['Button']
    'Calendar': typeof import("../components/ui/calendar/index")['Calendar']
    'CalendarCell': typeof import("../components/ui/calendar/index")['CalendarCell']
    'CalendarCellTrigger': typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
    'CalendarGrid': typeof import("../components/ui/calendar/index")['CalendarGrid']
    'CalendarGridBody': typeof import("../components/ui/calendar/index")['CalendarGridBody']
    'CalendarGridHead': typeof import("../components/ui/calendar/index")['CalendarGridHead']
    'CalendarGridRow': typeof import("../components/ui/calendar/index")['CalendarGridRow']
    'CalendarHeadCell': typeof import("../components/ui/calendar/index")['CalendarHeadCell']
    'CalendarHeader': typeof import("../components/ui/calendar/index")['CalendarHeader']
    'CalendarHeading': typeof import("../components/ui/calendar/index")['CalendarHeading']
    'CalendarNextButton': typeof import("../components/ui/calendar/index")['CalendarNextButton']
    'CalendarPrevButton': typeof import("../components/ui/calendar/index")['CalendarPrevButton']
    'Card': typeof import("../components/ui/card/index")['Card']
    'CardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'CardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'CardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'CardContent': typeof import("../components/ui/card/index")['CardContent']
    'CardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'Carousel': typeof import("../components/ui/carousel/index")['Carousel']
    'CarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'CarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'CarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'CarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'CarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'Checkbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'Dialog': typeof import("../components/ui/dialog/index")['Dialog']
    'DialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'DialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'DialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'DialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'DialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'DialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'DialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'DialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'DrawerPortal': typeof import("../components/ui/drawer/index")['DrawerPortal']
    'DrawerTrigger': typeof import("../components/ui/drawer/index")['DrawerTrigger']
    'DrawerClose': typeof import("../components/ui/drawer/index")['DrawerClose']
    'Drawer': typeof import("../components/ui/drawer/index")['Drawer']
    'DrawerOverlay': typeof import("../components/ui/drawer/index")['DrawerOverlay']
    'DrawerContent': typeof import("../components/ui/drawer/index")['DrawerContent']
    'DrawerHeader': typeof import("../components/ui/drawer/index")['DrawerHeader']
    'DrawerFooter': typeof import("../components/ui/drawer/index")['DrawerFooter']
    'DrawerTitle': typeof import("../components/ui/drawer/index")['DrawerTitle']
    'DrawerDescription': typeof import("../components/ui/drawer/index")['DrawerDescription']
    'DropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'DropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'DropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'DropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'DropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'DropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'DropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'DropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'DropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'DropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'DropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'DropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'DropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'DropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'DropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'Form': typeof import("../components/ui/form/index")['Form']
    'FormField': typeof import("../components/ui/form/index")['FormField']
    'FormFieldArray': typeof import("../components/ui/form/index")['FormFieldArray']
    'FormItem': typeof import("../components/ui/form/index")['FormItem']
    'FormLabel': typeof import("../components/ui/form/index")['FormLabel']
    'FormControl': typeof import("../components/ui/form/index")['FormControl']
    'FormMessage': typeof import("../components/ui/form/index")['FormMessage']
    'FormDescription': typeof import("../components/ui/form/index")['FormDescription']
    'FORMITEMINJECTIONKEY': typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
    'Input': typeof import("../components/ui/input/index")['Input']
    'Label': typeof import("../components/ui/label/index")['Label']
    'Pagination': typeof import("../components/ui/pagination/index")['Pagination']
    'PaginationList': typeof import("../components/ui/pagination/index")['PaginationList']
    'PaginationListItem': typeof import("../components/ui/pagination/index")['PaginationListItem']
    'PaginationEllipsis': typeof import("../components/ui/pagination/index")['PaginationEllipsis']
    'PaginationFirst': typeof import("../components/ui/pagination/index")['PaginationFirst']
    'PaginationLast': typeof import("../components/ui/pagination/index")['PaginationLast']
    'PaginationNext': typeof import("../components/ui/pagination/index")['PaginationNext']
    'PaginationPrev': typeof import("../components/ui/pagination/index")['PaginationPrev']
    'PopoverAnchor': typeof import("../components/ui/popover/index")['PopoverAnchor']
    'Popover': typeof import("../components/ui/popover/index")['Popover']
    'PopoverTrigger': typeof import("../components/ui/popover/index")['PopoverTrigger']
    'PopoverContent': typeof import("../components/ui/popover/index")['PopoverContent']
    'RangeCalendar': typeof import("../components/ui/range-calendar/index")['RangeCalendar']
    'RangeCalendarCell': typeof import("../components/ui/range-calendar/index")['RangeCalendarCell']
    'RangeCalendarCellTrigger': typeof import("../components/ui/range-calendar/index")['RangeCalendarCellTrigger']
    'RangeCalendarGrid': typeof import("../components/ui/range-calendar/index")['RangeCalendarGrid']
    'RangeCalendarGridBody': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridBody']
    'RangeCalendarGridHead': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridHead']
    'RangeCalendarGridRow': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridRow']
    'RangeCalendarHeadCell': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeadCell']
    'RangeCalendarHeader': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeader']
    'RangeCalendarHeading': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeading']
    'RangeCalendarNextButton': typeof import("../components/ui/range-calendar/index")['RangeCalendarNextButton']
    'RangeCalendarPrevButton': typeof import("../components/ui/range-calendar/index")['RangeCalendarPrevButton']
    'Separator': typeof import("../components/ui/separator/index")['Separator']
    'Sheet': typeof import("../components/ui/sheet/index")['Sheet']
    'SheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'SheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'SheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'SheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'SheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'SheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'SheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'Skeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'Toaster': typeof import("../components/ui/sonner/index")['Toaster']
    'Switch': typeof import("../components/ui/switch/index")['Switch']
    'Table': typeof import("../components/ui/table/index")['Table']
    'TableBody': typeof import("../components/ui/table/index")['TableBody']
    'TableCell': typeof import("../components/ui/table/index")['TableCell']
    'TableHead': typeof import("../components/ui/table/index")['TableHead']
    'TableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'TableFooter': typeof import("../components/ui/table/index")['TableFooter']
    'TableRow': typeof import("../components/ui/table/index")['TableRow']
    'TableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'TableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'Tabs': typeof import("../components/ui/tabs/index")['Tabs']
    'TabsTrigger': typeof import("../components/ui/tabs/index")['TabsTrigger']
    'TabsList': typeof import("../components/ui/tabs/index")['TabsList']
    'TabsContent': typeof import("../components/ui/tabs/index")['TabsContent']
    'Textarea': typeof import("../components/ui/textarea/index")['Textarea']
    'Tooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'TooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'TooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'TooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyNavbar': typeof import("../components/Navbar.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyAlert': typeof import("../components/ui/alert/index")['Alert']
    'LazyAlertTitle': typeof import("../components/ui/alert/index")['AlertTitle']
    'LazyAlertDescription': typeof import("../components/ui/alert/index")['AlertDescription']
    'LazyAlertDialog': typeof import("../components/ui/alert-dialog/index")['AlertDialog']
    'LazyAlertDialogTrigger': typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
    'LazyAlertDialogContent': typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
    'LazyAlertDialogHeader': typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
    'LazyAlertDialogTitle': typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
    'LazyAlertDialogDescription': typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
    'LazyAlertDialogFooter': typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
    'LazyAlertDialogAction': typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
    'LazyAlertDialogCancel': typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
    'LazyAvatar': typeof import("../components/ui/avatar/index")['Avatar']
    'LazyAvatarImage': typeof import("../components/ui/avatar/index")['AvatarImage']
    'LazyAvatarFallback': typeof import("../components/ui/avatar/index")['AvatarFallback']
    'LazyBadge': typeof import("../components/ui/badge/index")['Badge']
    'LazyBreadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'LazyBreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'LazyBreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'LazyBreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'LazyBreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'LazyBreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'LazyBreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'LazyButton': typeof import("../components/ui/button/index")['Button']
    'LazyCalendar': typeof import("../components/ui/calendar/index")['Calendar']
    'LazyCalendarCell': typeof import("../components/ui/calendar/index")['CalendarCell']
    'LazyCalendarCellTrigger': typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
    'LazyCalendarGrid': typeof import("../components/ui/calendar/index")['CalendarGrid']
    'LazyCalendarGridBody': typeof import("../components/ui/calendar/index")['CalendarGridBody']
    'LazyCalendarGridHead': typeof import("../components/ui/calendar/index")['CalendarGridHead']
    'LazyCalendarGridRow': typeof import("../components/ui/calendar/index")['CalendarGridRow']
    'LazyCalendarHeadCell': typeof import("../components/ui/calendar/index")['CalendarHeadCell']
    'LazyCalendarHeader': typeof import("../components/ui/calendar/index")['CalendarHeader']
    'LazyCalendarHeading': typeof import("../components/ui/calendar/index")['CalendarHeading']
    'LazyCalendarNextButton': typeof import("../components/ui/calendar/index")['CalendarNextButton']
    'LazyCalendarPrevButton': typeof import("../components/ui/calendar/index")['CalendarPrevButton']
    'LazyCard': typeof import("../components/ui/card/index")['Card']
    'LazyCardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'LazyCardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'LazyCardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'LazyCardContent': typeof import("../components/ui/card/index")['CardContent']
    'LazyCardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'LazyCarousel': typeof import("../components/ui/carousel/index")['Carousel']
    'LazyCarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'LazyCarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'LazyCarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'LazyCarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'LazyCarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'LazyCheckbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'LazyDialog': typeof import("../components/ui/dialog/index")['Dialog']
    'LazyDialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'LazyDialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'LazyDialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'LazyDialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'LazyDialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'LazyDialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'LazyDialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'LazyDialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'LazyDrawerPortal': typeof import("../components/ui/drawer/index")['DrawerPortal']
    'LazyDrawerTrigger': typeof import("../components/ui/drawer/index")['DrawerTrigger']
    'LazyDrawerClose': typeof import("../components/ui/drawer/index")['DrawerClose']
    'LazyDrawer': typeof import("../components/ui/drawer/index")['Drawer']
    'LazyDrawerOverlay': typeof import("../components/ui/drawer/index")['DrawerOverlay']
    'LazyDrawerContent': typeof import("../components/ui/drawer/index")['DrawerContent']
    'LazyDrawerHeader': typeof import("../components/ui/drawer/index")['DrawerHeader']
    'LazyDrawerFooter': typeof import("../components/ui/drawer/index")['DrawerFooter']
    'LazyDrawerTitle': typeof import("../components/ui/drawer/index")['DrawerTitle']
    'LazyDrawerDescription': typeof import("../components/ui/drawer/index")['DrawerDescription']
    'LazyDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'LazyDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'LazyDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'LazyDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'LazyDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'LazyDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'LazyDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'LazyDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'LazyDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'LazyDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'LazyDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'LazyDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'LazyDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'LazyDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'LazyDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'LazyForm': typeof import("../components/ui/form/index")['Form']
    'LazyFormField': typeof import("../components/ui/form/index")['FormField']
    'LazyFormFieldArray': typeof import("../components/ui/form/index")['FormFieldArray']
    'LazyFormItem': typeof import("../components/ui/form/index")['FormItem']
    'LazyFormLabel': typeof import("../components/ui/form/index")['FormLabel']
    'LazyFormControl': typeof import("../components/ui/form/index")['FormControl']
    'LazyFormMessage': typeof import("../components/ui/form/index")['FormMessage']
    'LazyFormDescription': typeof import("../components/ui/form/index")['FormDescription']
    'LazyFORMITEMINJECTIONKEY': typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
    'LazyInput': typeof import("../components/ui/input/index")['Input']
    'LazyLabel': typeof import("../components/ui/label/index")['Label']
    'LazyPagination': typeof import("../components/ui/pagination/index")['Pagination']
    'LazyPaginationList': typeof import("../components/ui/pagination/index")['PaginationList']
    'LazyPaginationListItem': typeof import("../components/ui/pagination/index")['PaginationListItem']
    'LazyPaginationEllipsis': typeof import("../components/ui/pagination/index")['PaginationEllipsis']
    'LazyPaginationFirst': typeof import("../components/ui/pagination/index")['PaginationFirst']
    'LazyPaginationLast': typeof import("../components/ui/pagination/index")['PaginationLast']
    'LazyPaginationNext': typeof import("../components/ui/pagination/index")['PaginationNext']
    'LazyPaginationPrev': typeof import("../components/ui/pagination/index")['PaginationPrev']
    'LazyPopoverAnchor': typeof import("../components/ui/popover/index")['PopoverAnchor']
    'LazyPopover': typeof import("../components/ui/popover/index")['Popover']
    'LazyPopoverTrigger': typeof import("../components/ui/popover/index")['PopoverTrigger']
    'LazyPopoverContent': typeof import("../components/ui/popover/index")['PopoverContent']
    'LazyRangeCalendar': typeof import("../components/ui/range-calendar/index")['RangeCalendar']
    'LazyRangeCalendarCell': typeof import("../components/ui/range-calendar/index")['RangeCalendarCell']
    'LazyRangeCalendarCellTrigger': typeof import("../components/ui/range-calendar/index")['RangeCalendarCellTrigger']
    'LazyRangeCalendarGrid': typeof import("../components/ui/range-calendar/index")['RangeCalendarGrid']
    'LazyRangeCalendarGridBody': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridBody']
    'LazyRangeCalendarGridHead': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridHead']
    'LazyRangeCalendarGridRow': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridRow']
    'LazyRangeCalendarHeadCell': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeadCell']
    'LazyRangeCalendarHeader': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeader']
    'LazyRangeCalendarHeading': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeading']
    'LazyRangeCalendarNextButton': typeof import("../components/ui/range-calendar/index")['RangeCalendarNextButton']
    'LazyRangeCalendarPrevButton': typeof import("../components/ui/range-calendar/index")['RangeCalendarPrevButton']
    'LazySeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazySheet': typeof import("../components/ui/sheet/index")['Sheet']
    'LazySheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'LazySheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'LazySheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'LazySheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'LazySheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'LazySheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'LazySheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'LazySkeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'LazyToaster': typeof import("../components/ui/sonner/index")['Toaster']
    'LazySwitch': typeof import("../components/ui/switch/index")['Switch']
    'LazyTable': typeof import("../components/ui/table/index")['Table']
    'LazyTableBody': typeof import("../components/ui/table/index")['TableBody']
    'LazyTableCell': typeof import("../components/ui/table/index")['TableCell']
    'LazyTableHead': typeof import("../components/ui/table/index")['TableHead']
    'LazyTableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'LazyTableFooter': typeof import("../components/ui/table/index")['TableFooter']
    'LazyTableRow': typeof import("../components/ui/table/index")['TableRow']
    'LazyTableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'LazyTableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'LazyTabs': typeof import("../components/ui/tabs/index")['Tabs']
    'LazyTabsTrigger': typeof import("../components/ui/tabs/index")['TabsTrigger']
    'LazyTabsList': typeof import("../components/ui/tabs/index")['TabsList']
    'LazyTabsContent': typeof import("../components/ui/tabs/index")['TabsContent']
    'LazyTextarea': typeof import("../components/ui/textarea/index")['Textarea']
    'LazyTooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'LazyTooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'LazyTooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'LazyTooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Footer: typeof import("../components/Footer.vue")['default']
export const Navbar: typeof import("../components/Navbar.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const Alert: typeof import("../components/ui/alert/index")['Alert']
export const AlertTitle: typeof import("../components/ui/alert/index")['AlertTitle']
export const AlertDescription: typeof import("../components/ui/alert/index")['AlertDescription']
export const AlertDialog: typeof import("../components/ui/alert-dialog/index")['AlertDialog']
export const AlertDialogTrigger: typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
export const AlertDialogContent: typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
export const AlertDialogHeader: typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
export const AlertDialogTitle: typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
export const AlertDialogDescription: typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
export const AlertDialogFooter: typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
export const AlertDialogAction: typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
export const AlertDialogCancel: typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
export const Avatar: typeof import("../components/ui/avatar/index")['Avatar']
export const AvatarImage: typeof import("../components/ui/avatar/index")['AvatarImage']
export const AvatarFallback: typeof import("../components/ui/avatar/index")['AvatarFallback']
export const Badge: typeof import("../components/ui/badge/index")['Badge']
export const Breadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const BreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const BreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const BreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const BreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const BreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const BreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const Button: typeof import("../components/ui/button/index")['Button']
export const Calendar: typeof import("../components/ui/calendar/index")['Calendar']
export const CalendarCell: typeof import("../components/ui/calendar/index")['CalendarCell']
export const CalendarCellTrigger: typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
export const CalendarGrid: typeof import("../components/ui/calendar/index")['CalendarGrid']
export const CalendarGridBody: typeof import("../components/ui/calendar/index")['CalendarGridBody']
export const CalendarGridHead: typeof import("../components/ui/calendar/index")['CalendarGridHead']
export const CalendarGridRow: typeof import("../components/ui/calendar/index")['CalendarGridRow']
export const CalendarHeadCell: typeof import("../components/ui/calendar/index")['CalendarHeadCell']
export const CalendarHeader: typeof import("../components/ui/calendar/index")['CalendarHeader']
export const CalendarHeading: typeof import("../components/ui/calendar/index")['CalendarHeading']
export const CalendarNextButton: typeof import("../components/ui/calendar/index")['CalendarNextButton']
export const CalendarPrevButton: typeof import("../components/ui/calendar/index")['CalendarPrevButton']
export const Card: typeof import("../components/ui/card/index")['Card']
export const CardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const CardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const CardContent: typeof import("../components/ui/card/index")['CardContent']
export const CardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const Carousel: typeof import("../components/ui/carousel/index")['Carousel']
export const CarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const CarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const CarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const CarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const CarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const Checkbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const Dialog: typeof import("../components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const DialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const DialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const DialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const DialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const DialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const DialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const DialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const DrawerPortal: typeof import("../components/ui/drawer/index")['DrawerPortal']
export const DrawerTrigger: typeof import("../components/ui/drawer/index")['DrawerTrigger']
export const DrawerClose: typeof import("../components/ui/drawer/index")['DrawerClose']
export const Drawer: typeof import("../components/ui/drawer/index")['Drawer']
export const DrawerOverlay: typeof import("../components/ui/drawer/index")['DrawerOverlay']
export const DrawerContent: typeof import("../components/ui/drawer/index")['DrawerContent']
export const DrawerHeader: typeof import("../components/ui/drawer/index")['DrawerHeader']
export const DrawerFooter: typeof import("../components/ui/drawer/index")['DrawerFooter']
export const DrawerTitle: typeof import("../components/ui/drawer/index")['DrawerTitle']
export const DrawerDescription: typeof import("../components/ui/drawer/index")['DrawerDescription']
export const DropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const Form: typeof import("../components/ui/form/index")['Form']
export const FormField: typeof import("../components/ui/form/index")['FormField']
export const FormFieldArray: typeof import("../components/ui/form/index")['FormFieldArray']
export const FormItem: typeof import("../components/ui/form/index")['FormItem']
export const FormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const FormControl: typeof import("../components/ui/form/index")['FormControl']
export const FormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const FormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const FORMITEMINJECTIONKEY: typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
export const Input: typeof import("../components/ui/input/index")['Input']
export const Label: typeof import("../components/ui/label/index")['Label']
export const Pagination: typeof import("../components/ui/pagination/index")['Pagination']
export const PaginationList: typeof import("../components/ui/pagination/index")['PaginationList']
export const PaginationListItem: typeof import("../components/ui/pagination/index")['PaginationListItem']
export const PaginationEllipsis: typeof import("../components/ui/pagination/index")['PaginationEllipsis']
export const PaginationFirst: typeof import("../components/ui/pagination/index")['PaginationFirst']
export const PaginationLast: typeof import("../components/ui/pagination/index")['PaginationLast']
export const PaginationNext: typeof import("../components/ui/pagination/index")['PaginationNext']
export const PaginationPrev: typeof import("../components/ui/pagination/index")['PaginationPrev']
export const PopoverAnchor: typeof import("../components/ui/popover/index")['PopoverAnchor']
export const Popover: typeof import("../components/ui/popover/index")['Popover']
export const PopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const PopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const RangeCalendar: typeof import("../components/ui/range-calendar/index")['RangeCalendar']
export const RangeCalendarCell: typeof import("../components/ui/range-calendar/index")['RangeCalendarCell']
export const RangeCalendarCellTrigger: typeof import("../components/ui/range-calendar/index")['RangeCalendarCellTrigger']
export const RangeCalendarGrid: typeof import("../components/ui/range-calendar/index")['RangeCalendarGrid']
export const RangeCalendarGridBody: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridBody']
export const RangeCalendarGridHead: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridHead']
export const RangeCalendarGridRow: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridRow']
export const RangeCalendarHeadCell: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeadCell']
export const RangeCalendarHeader: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeader']
export const RangeCalendarHeading: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeading']
export const RangeCalendarNextButton: typeof import("../components/ui/range-calendar/index")['RangeCalendarNextButton']
export const RangeCalendarPrevButton: typeof import("../components/ui/range-calendar/index")['RangeCalendarPrevButton']
export const Separator: typeof import("../components/ui/separator/index")['Separator']
export const Sheet: typeof import("../components/ui/sheet/index")['Sheet']
export const SheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const SheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const SheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const SheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const SheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const SheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const SheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const Skeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const Toaster: typeof import("../components/ui/sonner/index")['Toaster']
export const Switch: typeof import("../components/ui/switch/index")['Switch']
export const Table: typeof import("../components/ui/table/index")['Table']
export const TableBody: typeof import("../components/ui/table/index")['TableBody']
export const TableCell: typeof import("../components/ui/table/index")['TableCell']
export const TableHead: typeof import("../components/ui/table/index")['TableHead']
export const TableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const TableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const TableRow: typeof import("../components/ui/table/index")['TableRow']
export const TableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const TableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const Tabs: typeof import("../components/ui/tabs/index")['Tabs']
export const TabsTrigger: typeof import("../components/ui/tabs/index")['TabsTrigger']
export const TabsList: typeof import("../components/ui/tabs/index")['TabsList']
export const TabsContent: typeof import("../components/ui/tabs/index")['TabsContent']
export const Textarea: typeof import("../components/ui/textarea/index")['Textarea']
export const Tooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const TooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const TooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const TooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyNavbar: typeof import("../components/Navbar.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyAlert: typeof import("../components/ui/alert/index")['Alert']
export const LazyAlertTitle: typeof import("../components/ui/alert/index")['AlertTitle']
export const LazyAlertDescription: typeof import("../components/ui/alert/index")['AlertDescription']
export const LazyAlertDialog: typeof import("../components/ui/alert-dialog/index")['AlertDialog']
export const LazyAlertDialogTrigger: typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
export const LazyAlertDialogContent: typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
export const LazyAlertDialogHeader: typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
export const LazyAlertDialogTitle: typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
export const LazyAlertDialogDescription: typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
export const LazyAlertDialogFooter: typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
export const LazyAlertDialogAction: typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
export const LazyAlertDialogCancel: typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
export const LazyAvatar: typeof import("../components/ui/avatar/index")['Avatar']
export const LazyAvatarImage: typeof import("../components/ui/avatar/index")['AvatarImage']
export const LazyAvatarFallback: typeof import("../components/ui/avatar/index")['AvatarFallback']
export const LazyBadge: typeof import("../components/ui/badge/index")['Badge']
export const LazyBreadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const LazyBreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const LazyBreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const LazyBreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const LazyBreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const LazyBreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const LazyBreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const LazyButton: typeof import("../components/ui/button/index")['Button']
export const LazyCalendar: typeof import("../components/ui/calendar/index")['Calendar']
export const LazyCalendarCell: typeof import("../components/ui/calendar/index")['CalendarCell']
export const LazyCalendarCellTrigger: typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
export const LazyCalendarGrid: typeof import("../components/ui/calendar/index")['CalendarGrid']
export const LazyCalendarGridBody: typeof import("../components/ui/calendar/index")['CalendarGridBody']
export const LazyCalendarGridHead: typeof import("../components/ui/calendar/index")['CalendarGridHead']
export const LazyCalendarGridRow: typeof import("../components/ui/calendar/index")['CalendarGridRow']
export const LazyCalendarHeadCell: typeof import("../components/ui/calendar/index")['CalendarHeadCell']
export const LazyCalendarHeader: typeof import("../components/ui/calendar/index")['CalendarHeader']
export const LazyCalendarHeading: typeof import("../components/ui/calendar/index")['CalendarHeading']
export const LazyCalendarNextButton: typeof import("../components/ui/calendar/index")['CalendarNextButton']
export const LazyCalendarPrevButton: typeof import("../components/ui/calendar/index")['CalendarPrevButton']
export const LazyCard: typeof import("../components/ui/card/index")['Card']
export const LazyCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const LazyCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const LazyCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const LazyCardContent: typeof import("../components/ui/card/index")['CardContent']
export const LazyCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const LazyCarousel: typeof import("../components/ui/carousel/index")['Carousel']
export const LazyCarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const LazyCarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const LazyCarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const LazyCarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const LazyCarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const LazyCheckbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const LazyDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const LazyDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const LazyDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const LazyDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const LazyDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const LazyDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const LazyDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const LazyDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const LazyDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const LazyDrawerPortal: typeof import("../components/ui/drawer/index")['DrawerPortal']
export const LazyDrawerTrigger: typeof import("../components/ui/drawer/index")['DrawerTrigger']
export const LazyDrawerClose: typeof import("../components/ui/drawer/index")['DrawerClose']
export const LazyDrawer: typeof import("../components/ui/drawer/index")['Drawer']
export const LazyDrawerOverlay: typeof import("../components/ui/drawer/index")['DrawerOverlay']
export const LazyDrawerContent: typeof import("../components/ui/drawer/index")['DrawerContent']
export const LazyDrawerHeader: typeof import("../components/ui/drawer/index")['DrawerHeader']
export const LazyDrawerFooter: typeof import("../components/ui/drawer/index")['DrawerFooter']
export const LazyDrawerTitle: typeof import("../components/ui/drawer/index")['DrawerTitle']
export const LazyDrawerDescription: typeof import("../components/ui/drawer/index")['DrawerDescription']
export const LazyDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const LazyDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const LazyDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const LazyDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const LazyDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const LazyDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const LazyDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const LazyDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const LazyDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const LazyDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const LazyDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const LazyDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const LazyDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const LazyDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const LazyDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const LazyForm: typeof import("../components/ui/form/index")['Form']
export const LazyFormField: typeof import("../components/ui/form/index")['FormField']
export const LazyFormFieldArray: typeof import("../components/ui/form/index")['FormFieldArray']
export const LazyFormItem: typeof import("../components/ui/form/index")['FormItem']
export const LazyFormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const LazyFormControl: typeof import("../components/ui/form/index")['FormControl']
export const LazyFormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const LazyFormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const LazyFORMITEMINJECTIONKEY: typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
export const LazyInput: typeof import("../components/ui/input/index")['Input']
export const LazyLabel: typeof import("../components/ui/label/index")['Label']
export const LazyPagination: typeof import("../components/ui/pagination/index")['Pagination']
export const LazyPaginationList: typeof import("../components/ui/pagination/index")['PaginationList']
export const LazyPaginationListItem: typeof import("../components/ui/pagination/index")['PaginationListItem']
export const LazyPaginationEllipsis: typeof import("../components/ui/pagination/index")['PaginationEllipsis']
export const LazyPaginationFirst: typeof import("../components/ui/pagination/index")['PaginationFirst']
export const LazyPaginationLast: typeof import("../components/ui/pagination/index")['PaginationLast']
export const LazyPaginationNext: typeof import("../components/ui/pagination/index")['PaginationNext']
export const LazyPaginationPrev: typeof import("../components/ui/pagination/index")['PaginationPrev']
export const LazyPopoverAnchor: typeof import("../components/ui/popover/index")['PopoverAnchor']
export const LazyPopover: typeof import("../components/ui/popover/index")['Popover']
export const LazyPopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const LazyPopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const LazyRangeCalendar: typeof import("../components/ui/range-calendar/index")['RangeCalendar']
export const LazyRangeCalendarCell: typeof import("../components/ui/range-calendar/index")['RangeCalendarCell']
export const LazyRangeCalendarCellTrigger: typeof import("../components/ui/range-calendar/index")['RangeCalendarCellTrigger']
export const LazyRangeCalendarGrid: typeof import("../components/ui/range-calendar/index")['RangeCalendarGrid']
export const LazyRangeCalendarGridBody: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridBody']
export const LazyRangeCalendarGridHead: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridHead']
export const LazyRangeCalendarGridRow: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridRow']
export const LazyRangeCalendarHeadCell: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeadCell']
export const LazyRangeCalendarHeader: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeader']
export const LazyRangeCalendarHeading: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeading']
export const LazyRangeCalendarNextButton: typeof import("../components/ui/range-calendar/index")['RangeCalendarNextButton']
export const LazyRangeCalendarPrevButton: typeof import("../components/ui/range-calendar/index")['RangeCalendarPrevButton']
export const LazySeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazySheet: typeof import("../components/ui/sheet/index")['Sheet']
export const LazySheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const LazySheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const LazySheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const LazySheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const LazySheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const LazySheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const LazySheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const LazySkeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const LazyToaster: typeof import("../components/ui/sonner/index")['Toaster']
export const LazySwitch: typeof import("../components/ui/switch/index")['Switch']
export const LazyTable: typeof import("../components/ui/table/index")['Table']
export const LazyTableBody: typeof import("../components/ui/table/index")['TableBody']
export const LazyTableCell: typeof import("../components/ui/table/index")['TableCell']
export const LazyTableHead: typeof import("../components/ui/table/index")['TableHead']
export const LazyTableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const LazyTableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const LazyTableRow: typeof import("../components/ui/table/index")['TableRow']
export const LazyTableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const LazyTableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const LazyTabs: typeof import("../components/ui/tabs/index")['Tabs']
export const LazyTabsTrigger: typeof import("../components/ui/tabs/index")['TabsTrigger']
export const LazyTabsList: typeof import("../components/ui/tabs/index")['TabsList']
export const LazyTabsContent: typeof import("../components/ui/tabs/index")['TabsContent']
export const LazyTextarea: typeof import("../components/ui/textarea/index")['Textarea']
export const LazyTooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const LazyTooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const LazyTooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const LazyTooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
