// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/10/2024, 1:01:00 PM
const configMerger = require("/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/plugins/**/*.{js,ts,mjs}","/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/composables/**/*.{js,ts,mjs}","/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/utils/**/*.{js,ts,mjs}","/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/edwardmiller/Documents/GitHub/woofs-welcome-web/app.config.{js,ts,mjs}"] }));

module.exports = config
